### PR TITLE
bcftools stats QUAL plot

### PR DESCRIPTION
**Pull request by pdiakumis**
Initial draft. Grabbing the QUAL rows from the `<sampleid>.somatic.bcftools_stats.txt` file and generating a histo + density plot for just the SNPs. Plot shows total count of SNPs in the title, not sure which VCF gets fed to bcftools via bolt (@scwatts ?) so would be good to confirm some numbers.

For comparison this is how that data looks like in the MultiQC report. Note that MultiQC grabs max 600 points and I think sums the in-between counts into bins - see https://github.com/MultiQC/MultiQC/blob/main/multiqc/modules/bcftools/stats.py#L278.

multiqc

Fyi @ohofmann

### CODE REVIEW

**Comment by scwatts** [comment]
The input VCF used to generate the somatic BCFtools stats (`smlv_somatic/report/*.somatic.bcftools_stats.txt`) is the filtered somatic VCF (`smlv_somatic/filter/*.pass.vcf.gz`).

The plot looks good! Particularly compared to the MultiQC equivalent - I'll be fixing the bin size in the next round of sash/bolt work, which will begin in ~1 week.

**Comment by pdiakumis** [comment]
Okay, that makes sense, total SNPs stack up with total counts of QUAL rows in `somatic.bcftools_stats.txt` shown in the plot title:

```
"MDX240005.pass.vcf.gz" |>
  dracarys::bcftools_parse_vcf(only_pass = F) |>
  select(REF, ALT, S2_SQ) |>
  mutate(is_snp = (nchar(REF) == 1) & (nchar(ALT) == 1)) |>
  count(is_snp)

  is_snp     n
  <lgl>  <int>
1 FALSE    198
2 TRUE    2749
```

**Comment by ohofmann** [comment]
That graph is a lot more useful than the MultiQC one!

**Review by scwatts — APPROVED** [review]
LGTM!

**Pull request merged**
